### PR TITLE
Add Sway test to Leap 15 and TW

### PR DESCRIPTION
**Pull request by richiejp**
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17285

### CODE REVIEW

**Comment by richiejp** [comment]
@foursixnine @DimStar77

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/3373166

```
Reason: asset failure: Failed to download opensuse-Tumbleweed-x86_64-20230621-textmode@64bit_virtio.qcow2 to /var/lib/openqa/cache/openqa1-opensuse/opensuse-Tumbleweed-x86_64-20230621-textmode@64bit_virtio.qcow2 
```

**Comment by richiejp** [comment]
hhmm, I see the machine name doesn't match the create_hdd_textmode job. On my local setup I set `QEMU_VIDEO_DEVICE: virtio-vga` on the testsuite instead of changing the machine.

**Comment by richiejp** [comment]
https://openqa.opensuse.org/tests/3373896

**Pull request merged**
