### PR TITLE
Update Windows installation jobgroup

### PR DESCRIPTION
**Pull request by pablo-herranz**
The jobgroup for installing Windows is obsolete since some years ago. This changes are for syncing the jobgroup to the OSD status

### CODE REVIEW

**Comment by Vogtinator** [comment]
Is this actually used/useful?

**Comment by pablo-herranz** [comment]
> Is this actually used/useful?

Currently, whenever any change is done to the `qcow2` images, there's need to clone them from OSD to O3, and though there's not a direct connection between the machines, I guess to run the installation in both test environments would be time-saving.

**Comment by Vogtinator** [comment]
> > Is this actually used/useful?
> 
> Currently, whenever any change is done to the `qcow2` images, there's need to clone them from OSD to O3, and though there's not a direct connection between the machines, I guess to run the installation in both test environments would be time-saving.

Sounds like o3 should become the authoritative source for the installation jobs and images then?

**Comment by pablo-herranz** [comment]
> > > Is this actually used/useful?
> > 
> > 
> > Currently, whenever any change is done to the `qcow2` images, there's need to clone them from OSD to O3, and though there's not a direct connection between the machines, I guess to run the installation in both test environments would be time-saving.
> 
> Sounds like o3 should become the authoritative source for the installation jobs and images then?

Wouldn't it be necessary to copy the qcow images from O3 to OSD then later?

I also don't like to have duplicated jobs, but didn't find a better solution...

**Comment by grisu48** [comment]
> > o3 is "upstream" so if possible it should be the development target.
> 
> Seems ok for me but I'd like to know @mloviska 's point-of-view

This sounds like a good approach to me. We can re-use resources from O3, and if this makes our life easier, then let's go for it.

**Comment by mloviska** [comment]
> Seems ok for me but I'd like to know @mloviska 's point-of-view

FTR, we have already jobs in o3 that are installing windows images. For win10 we also have dedicated regcodes for o3 and OSD. I do not mind sharing the images as long as there is no non-technical issue involved here.

**Pull request merged**
