### PR TITLE
Add upgrade tests from leap15.5/15.6 to tw

### PR DESCRIPTION
**Pull request by rfan1**
https://progress.opensuse.org/issues/131312

VR: 
[leap to tw](https://openqa.opensuse.org/tests/overview?distri=opensuse&version=Tumbleweed&build=20240524&groupid=119)
[leap to leap](https://openqa.opensuse.org/tests/overview?version=15.6&distri=opensuse&build=rfan0527)
[leap to leap MU](https://openqa.opensuse.org/tests/overview?version=15.6&build=rfan0527_mu&distri=opensuse)
1. DVD-Upgrade
2. ZDUP
3. LIVE Upgrade

### CODE REVIEW

**Comment by rfan1** [comment]
@foursixnine can you please help review?

**Review by dzedro — APPROVED** [review]

**Review by foursixnine — APPROVED** [review]

**Comment by rfan1** [comment]
Please wait for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19337 gets merged :)

**Comment by Vogtinator** [comment]
Can you try a 15.5 LIVE_UPGRADE test as well?

**Comment by rfan1** [comment]
> Can you try a 15.5 LIVE_UPGRADE test as well?

Sure

**Review by foursixnine — APPROVED** [review]

**Review by nilxam — APPROVED** [review]

**Pull request merged**
