### PR TITLE
Leap15.4: Increase coverage of Updates testing

### PR DESCRIPTION
**Pull request by mloviska**

### CODE REVIEW

**Comment by mloviska** [comment]
Hm... looking at https://github.com/openSUSE/openSUSE-release-tools/blob/master/data/incidents.json, maybe we should separate `aarch64` in a different PR and first configure the bot for `aarch64`

**Comment by mloviska** [comment]
https://github.com/openSUSE/openSUSE-release-tools/pull/2830

**Review by asdil12 — APPROVED** [review]

**Comment by okurz** [comment]
This caused a regression https://progress.opensuse.org/issues/116878 due to the removal of "kde". The regression is fixed in https://github.com/openSUSE/openSUSE-release-tools/pull/2872.

But I wonder, is it really intended to remove the kde testsuite? Because I assume that still the kde testsuite has test modules scheduled which "create_hdd_kde+extra_tests_kde" do not necessarily have yet.

**Comment by mloviska** [comment]
> But I wonder, is it really intended to remove the kde testsuite? Because I assume that still the kde testsuite has test modules scheduled which "create_hdd_kde+extra_tests_kde" do not necessarily have yet.

The idea was to start with a smaller test suite than the full-blown KDE. I haven't noticed it is mentioned in the release-tools, sorry for that. The x11 test cases are already covered in `zdup-Leap` scenarios.

**Comment by okurz** [comment]
> I haven't noticed it is mentioned in the release-tools, sorry for that.
No need to excuse. Likely no one has expected that :D

> The idea was to start with a smaller test suite than the full-blown KDE. […] The x11 test cases are already covered in `zdup-Leap` scenarios.

The idea is sane. The "zdup" case is doing something different though than the "clean install kde" case.

**Pull request merged**
