### PR TITLE
Schedule ping MM test

### PR DESCRIPTION
**Pull request by asdil12**
To be merged after https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/18440

### CODE REVIEW

**Review by Martchus — APPROVED** [review]

**Review by okurz — APPROVED** [review]

**Review by foursixnine — CHANGES_REQUESTED** [review]
See my review in the related PR. I see no point in adding a ping test, that is really just a verification. So you might need to adjust your ticket too and acceptance criteria.

**Comment by okurz** [comment]
@asdil12 see the above comment by foursixnine. That's why I stress so often the need for commit messages to make it clear why commits are needed and what's the added benefit

**Comment by asdil12** [comment]
@foursixnine I described in the other PR why this is needed.

**Comment by okurz** [comment]
> We use pull requests, not commit messages to propose changes. If there's an added benefit make it clear on the description ;), a great engineer recently said to me "think of people being lazy and having a short attention span" :)

Exactly. And thinking of engineers creating the changes originally I recommend to just write proper commit messages and use the same text in the description :)

**Comment by foursixnine** [comment]
> @foursixnine I described in the other PR why this is needed.

I don't have issues with this PR or the description, that's @okurz xD

**Review by foursixnine — APPROVED** [review]

**Comment by okurz** [comment]
> I don't have issues with this PR or the description, that's @okurz xD

can you approve the PR then? Because my comments didn't withhold my approval.

**Pull request merged**
