### PR TITLE
Add package in whitelist

### PR DESCRIPTION
**Pull request by punkioudi**
Because of the bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1199442
the package will be whitelisted.

Progress ticket: https://progress.opensuse.org/issues/111144

### CODE REVIEW

**Comment by mloviska** [comment]
I would honestly wait with this one, as it is not clear to me whether Leap15.3 should contain `python2` packages or not. If python2 is still supported, the package should be published in a repository. If it has somehow slipped into the iso, there is not much to do just to whitelist it.

**Comment by punkioudi** [comment]
> I would honestly wait with this one, as it is not clear to me whether Leap15.3 should contain `python2` packages or not. If python2 is still supported, the package should be published in a repository. If it has somehow slipped into the iso, there is not much to do just to whitelist it.

Yes, indeed, but for now we have to workaround it as 5 testsuites are failing in o3 Leap 15.3 Updates and are blocking the queue.

**Comment by punkioudi** [comment]
Yes indeed, but I wanted to workaround it to release the queue. In any case though this issue doesn't appear anymore: https://openqa.opensuse.org/tests/overview?distri=opensuse&version=15.3&build=20220517-1&groupid=80. The new issue seems to be similar, but it happens with another package -> `libreoffice-gtk2`

**Comment by mloviska** [comment]
> Yes indeed, but I wanted to workaround it to release the queue. In any case though this issue doesn't appear anymore: https://openqa.opensuse.org/tests/overview?distri=opensuse&version=15.3&build=20220517-1&groupid=80. The new issue seems to be similar, but it happens with another package -> `libreoffice-gtk2`

Isn't it enough to label the failed tests ? Shouldn't `ttm` handle it afterwards?

**Pull request closed without merging**
