### PR TITLE
Use registry.qe.suse.de

### PR DESCRIPTION
**Pull request by ricardobranco777**
Use registry.qe.suse.de

Related ticket: https://progress.opensuse.org/issues/98415
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1146

Verification runs:
- https://openqa.suse.de/tests/10811197
-

### CODE REVIEW

**Comment by pdostal** [comment]
Did you check the DNS on o3?

**Comment by ricardobranco777** [comment]
> Did you check the DNS on o3?

No because I'm having issues cloning jobs from o3.

**Review by jlausuch — CHANGES_REQUESTED** [review]
Looks like we have an issue in O3, so I will block the merge of this PR.
https://openqa.opensuse.org/tests/3195003#step/podman/57
```
Trying to pull registry.qe.suse.de:5000/library/alpine:latest...
Error: initializing source docker://registry.qe.suse.de:5000/library/alpine:latest: pinging container registry registry.qe.suse.de:5000: Get "http://registry.qe.suse.de:5000/v2/": dial tcp: lookup registry.qe.suse.de on 10.0.2.3:53: no such host
```

**Comment by ricardobranco777** [comment]
> Looks like we have an issue in O3, so I will block the merge of this PR. https://openqa.opensuse.org/tests/3195003#step/podman/57
> 
> ```
> Trying to pull registry.qe.suse.de:5000/library/alpine:latest...
> Error: initializing source docker://registry.qe.suse.de:5000/library/alpine:latest: pinging container registry registry.qe.suse.de:5000: Get "http://registry.qe.suse.de:5000/v2/": dial tcp: lookup registry.qe.suse.de on 10.0.2.3:53: no such host
> ```

I notified about this in the SD ticket.

The related MR was merged.  Shall we revert?

**Pull request closed without merging**
