### PR TITLE
Add zdup test from the latest tumbleweed snapshot

### PR DESCRIPTION
**Pull request by rfan1**
https://progress.opensuse.org/issues/16618

Please see https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17043 for code changes and VRs

### CODE REVIEW

**Comment by rfan1** [comment]
@DimStar77 @foursixnine 

Would you please help review this PR? thanks much!

**Comment by DimStar77** [comment]
Curious: isn't that the very same we already test here:

https://openqa.opensuse.org/tests/3284245#dependencies

I.e e install a HDD with ''currently published TW' and in step tiro two upgrade that image to the two snapshot under test?

**Comment by rfan1** [comment]
> Curious: isn't that the very same we already test here:
> 
> https://openqa.opensuse.org/tests/3284245#dependencies
> 
> I.e e install a HDD with ''currently published TW' and in step tiro two upgrade that image to the two snapshot under test?

The small difference is ISO image. I used the released one:

SO=
ISO_1=openSUSE-Tumbleweed-DVD-x86_64-%BUILD%-Current.iso
ISO_1_URL=https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-DVD-x86_64-Current.iso

**Comment by DimStar77** [comment]
I fail to see much difference - your variant is slightly cleaner as it uses the already published ISO to start the installation - and then uses autoyast to actually perform the installation, in contrast to the existing tests using the 'NET ISO to be tested' and kexec into the published environment - then install from the published snapshot

(existing ones exist for GNOME and KDE already - your new variant only proposes GNOME so far)

so the question should be: what documented requirement is not yet covered with the already existing test?

**Comment by rfan1** [comment]
Thank you for the update!

I don't think the existing tests are missing some coverage! the only thing is that I used released ISO as a installation media.
But, I don't think it can give much difference based on the zdup tests, we still need do update the system via the to be release repositories.


Let me close my ticket then.

**Pull request closed without merging**
