### PR TITLE
microos-*-MicroOS-Image-aarch64: Align aarch64 on x86_64

### PR DESCRIPTION
**Pull request by ggardet**

### CODE REVIEW

**Comment by lkocman** [comment]
@sysrich we have this for Leap Micro tested and on get-o-o, the idea is to backport the same for MicroOS

**Comment by asdil12** [comment]
Please look at https://github.com/os-autoinst/opensuse-jobgroups/pull/133/files to see what the CI complained about.

**Comment by foursixnine** [comment]
@asdil12 @tinita is there a way to check the indentation similar to our `make tidy` target for os-autoinst-distri-opensuse?

**Comment by ggardet** [comment]
Yes, I am on it with `yamllint -f github job_groups.yaml job_groups/opensuse_tumbleweed_aarch64.yaml`

**Comment by ggardet** [comment]
@asdil12 The remaining CI failure are for other files. Could we merge this PR anyway?

**Comment by asdil12** [comment]
> @asdil12 @perlpunk is there a way to check the indentation similar to our `make tidy` target for os-autoinst-distri-opensuse?

I don't know what `make tidy` does exactly but the CI checks that.
I'm not sure what else you want to see? Is this about performing the check locally?
Or about automatic tidying?

**Comment by asdil12** [comment]
> @asdil12 The remaining CI failure are for other files. Could we merge this PR anyway?

You could to a rebase to current master to fix the ci.

**Comment by ggardet** [comment]
I rebased and now the CI errors are different, but I cannot understand how to fix it.

**Comment by asdil12** [comment]
Now that the yaml lint is more or less done, the ci went to the next step and asked the openqa.opensuse.org server to verify the yaml code. This is the same error message you would get on the openqa webui.
```
Error 400:
  YAML Path: /scenarios/aarch64/opensuse-Tumbleweed-GNOME-Live-aarch64/0
  Message: /anyOf/1 Too many properties: 2/1.
```

**Comment by ggardet** [comment]
> Now that the yaml lint is more or less done, the ci went to the next step and asked the openqa.opensuse.org server to verify the yaml code. This is the same error message you would get on the openqa webui.
> 
> ```
> Error 400:
>   YAML Path: /scenarios/aarch64/opensuse-Tumbleweed-GNOME-Live-aarch64/0
>   Message: /anyOf/1 Too many properties: 2/1.
> ```

No idea what it means, so no idea how to fix it.

**Comment by foursixnine** [comment]
> > @asdil12 @perlpunk is there a way to check the indentation similar to our `make tidy` target for os-autoinst-distri-opensuse?
> 
> I don't know what `make tidy` does exactly internally but the CI checks yaml indentation. I'm not sure what else you want to see? Is this about performing the check locally? Or about automatic tidying?

Automatic tidying, `make tidy` uses perltidy internally, so I guess there's something for yaml

**Comment by perlpunk** [comment]
there's https://perlpunk.github.io/yamltidy/
but it's still quite new.
not in opensuse yet, but can be called via a (very small) container.
right now it doesn't have a mode for scanning a directory, it can only tidy one file at a time.

there's also a yaml plugin for `prettier`, it's also very new. i think it doesn't have much configuration options yet, I haven't tried it out yet

**Comment by asdil12** [comment]
The problem here is that yaml in its incredible wisdom differentiates according to indentation:
These two yaml snippets are both valid yaml that would be accepted by the server but yamllint would print an error like `wrong indentation: expected 6 but found 4  (indentation)` for the `- openqa_install+publish:` line in the first example.
The only difference is that all lines including and after `- openqa_install+publish:` have been prefixed with two extra spaces in the 2nd example. This is what we want.

```yaml
scenarios:
  x86_64:
    openqa-*-dev-x86_64:
    - openqa_install+publish:
        testsuite: null
        settings:
          PUBLISH_HDD_1: 'opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%.qcow2'
          PUBLISH_PFLASH_VARS: 'opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%-uefi-vars.qcow2'
          PYTHON: '1'
        description: Blug
```

```yaml
scenarios:
  x86_64:
    openqa-*-dev-x86_64:
      - openqa_install+publish:
          testsuite: null
          settings:
            PUBLISH_HDD_1: 'opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%.qcow2'
            PUBLISH_PFLASH_VARS: 'opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%-uefi-vars.qcow2'
            PYTHON: '1'
          description: Blug
```

To fix the first example, one would be prone to just add these two spaces in front of the `- openqa_install+publish:` which would create something like this:
```yaml
scenarios:
  x86_64:
    openqa-*-dev-x86_64:
      - openqa_install+publish:
        testsuite: null
        settings:
          PUBLISH_HDD_1: 'opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%.qcow2'
          PUBLISH_PFLASH_VARS: 'opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%-uefi-vars.qcow2'
          PYTHON: '1'
        description: Blug
```
But this last example will produce this odd error messages. The reason is that the yaml SHOULD be equivalent to the following:
```json
    "scenarios": {
        "x86_64": {
            "openqa-*-dev-x86_64": [
                {
                    "openqa_install+publish": {
                        "description": "Maintainer: okurz@suse.de Test for installation of openQA itself. To be used with \"openqa\" distri. Publishes an qcow2 image including the openQA installation ready to run as an appliance.",
                        "settings": {
                            "PUBLISH_HDD_1": "opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%.qcow2",
                            "PUBLISH_PFLASH_VARS": "opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%-uefi-vars.qcow2",
                            "PYTHON": "1"
                        },
                        "testsuite": null
                    }
                },…
```

But the last example is equivalent to this:
```json
    "scenarios": {
        "x86_64": {
            "openqa-*-dev-x86_64": [
                {
                    "description": "Maintainer: okurz@suse.de Test for installation of openQA itself. To be used with \"openqa\" distri. Publishes an qcow2 image including the openQA installation ready to run as an appliance.",
                    "openqa_install+publish": null,
                    "settings": {
                        "PUBLISH_HDD_1": "opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%.qcow2",
                        "PUBLISH_PFLASH_VARS": "opensuse-Tumbleweed-%ARCH%@%MACHINE%-%BUILD%-uefi-vars.qcow2",
                        "PYTHON": "1"
                    },
                    "testsuite": null
                },…
```

**Comment by asdil12** [comment]
I pushed some fixes to this PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/133/commits/f23727bcd726532abc3a97aa1dc06ce2a7ac83c4
Now it seems to work.

**Comment by perlpunk** [comment]
> To fix the first example, one would be prone to just add these two spaces in front

yamltidy handles this well and will indent the whole block below that sequence item.

**Comment by asdil12** [comment]
@perlpunk it will generate yaml that the server will accept but at the samt time yamllint will complain about:
```
[dheidler@athene job_groups (master)]$ git diff opensuse_leap_15.4_backports.yaml
diff --git a/job_groups/opensuse_leap_15.4_backports.yaml b/job_groups/opensuse_leap_15.4_backports.yaml
index ed13848..68e0060 100644
--- a/job_groups/opensuse_leap_15.4_backports.yaml
+++ b/job_groups/opensuse_leap_15.4_backports.yaml
@@ -16,26 +16,26 @@ products:
   opensuse-15.4-DVD-Backports-Incidents-x86_64:
     distri: opensuse
     flavor: DVD-Backports-Incidents
-    version: '15.4'
+    version: 15.4
 scenarios:
   x86_64:
     opensuse-15.4-DVD-Backports-Incidents-x86_64:
-      - textmode:
-          machine: 64bit
-      - kde
-      - gnome:
-          machine: uefi
-          settings:
-            QEMUVGA: cirrus
-      - gnome:
-          machine: 64bit-2G
-          settings:
-            QEMUVGA: cirrus
-      - cryptlvm:
-          settings:
-            YAML_SCHEDULE: schedule/yast/opensuse/encryption/cryptlvm.yaml
-      - install_with_updates_gnome:
-          settings:
-            QEMUVGA: cirrus
-      - install_with_updates_kde:
-          machine: uefi-2G
+    - textmode:
+        machine: 64bit
+    - kde
+    - gnome:
+        machine: uefi
+        settings:
+          QEMUVGA: cirrus
+    - gnome:
+        machine: 64bit-2G
+        settings:
+          QEMUVGA: cirrus
+    - cryptlvm:
+        settings:
+          YAML_SCHEDULE: schedule/yast/opensuse/encryption/cryptlvm.yaml
+    - install_with_updates_gnome:
+        settings:
+          QEMUVGA: cirrus
+    - install_with_updates_kde:
+        machine: uefi-2G
[dheidler@athene job_groups (master)]$ yamllint opensuse_leap_15.4_backports.yaml
opensuse_leap_15.4_backports.yaml
  23:5      error    wrong indentation: expected 6 but found 4  (indentation)

**Comment by perlpunk** [comment]
@asdil12 that's a configuration issue. you need to tell yamltidy that you want to indent sequences in mappings. The default (and preferred by the yaml core team) format is to not indent those sequences.
Just look at the examples linked from the homepage: https://perlpunk.github.io/yamltidy/seqindent.html
Create a `.yamltidy` file like this in the current directory:
```
---
v: v0.1
indentation:
  spaces: 2
  block-sequence-in-mapping: 2
trailing-spaces: fix
scalar-style: { default }
```
If I use that on `opensuse_leap_15.4_backports.yaml` I get no changes at all.
```
% yamltidy --version
yamltidy:           0.005
YAML::PP:           0.032
YAML::LibYAML::API: 0.013
libyaml:            0.2.5
```

**Comment by asdil12** [comment]
https://github.com/os-autoinst/opensuse-jobgroups/pull/136

> But that the quotes around the `'15.4` are removed by default, is actually bug. I will look into that.
But that shouldn't break yamllint or the serverside check - am I right?

**Comment by perlpunk** [comment]
@asdil12 I finally fixed the quoting bug and released yamltidy 0.006 to CPAN https://metacpan.org/dist/YAML-Tidy and updated dockerhub https://hub.docker.com/r/perlpunk/yamltidy/tags
Now `scalar-style: { default: plain }` - which is the default - should work.

**Pull request merged**
