### PR TITLE
Enable Leap15.5 update tests on openQA

### PR DESCRIPTION
**Pull request by rfan1**
https://progress.opensuse.org/issues/116072

Added new coverage compare to Leap15.4 update test: upgrade Leap15.4 to Leap15.5

### CODE REVIEW

**Comment by rfan1** [comment]
@foursixnine @dzedro Would you please help review the upgrade test from `Leap15.2` and `Leap15.3`?

Seems they are EOL, can we remove them if possible?

**Comment by foursixnine** [comment]
> @foursixnine @dzedro Would you please help review the upgrade test from `Leap15.2` and `Leap15.3`?
> 
> Seems they are EOL, can we remove them if possible?

EOL products are out of scope

**Review by foursixnine — APPROVED** [review]

**Comment by rfan1** [comment]
> > @foursixnine @dzedro Would you please help review the upgrade test from `Leap15.2` and `Leap15.3`?
> > Seems they are EOL, can we remove them if possible?
> 
> EOL products are out of scope

Removed, thanks much!

**Review by dzedro — APPROVED** [review]

**Comment by rfan1** [comment]
Could you please help merge @foursixnine ？

**Pull request merged**
