### PR TITLE
Schedule network bonding test for microos

### PR DESCRIPTION
**Pull request by ilmanzo**
reference ticket: https://progress.opensuse.org/issues/151273
VR: https://openqa.opensuse.org/tests/3800277

### CODE REVIEW

**Comment by Vogtinator** [comment]
How useful is this as a separate job? It has only a single test module

**Comment by ilmanzo** [comment]
> How useful is this as a separate job? It has only a single test module

I could not find any "network-related" job, and it requires special network setup with two NICs on the same vlan. Do you suggest to schedule in an existing one ?

**Comment by foursixnine** [comment]
> How useful is this as a separate job? It has only a single test module.

Keeps the failures isolated, lets go for it, while its one more job, it is less likely to interfere with other test modules. (eventually to end up in the Network Stack)

**Comment by Vogtinator** [comment]
> > How useful is this as a separate job? It has only a single test module
> 
> I could not find any "network-related" microos job, and it requires special network setup with two NICs on the same vlan. Do you suggest to schedule in an existing one ?

Not necessarily, but maybe it would be useful to run some other network related modules in the same job to make sure they work in a bonding setup as well?

**Comment by ilmanzo** [comment]
> > > How useful is this as a separate job? It has only a single test module
> > 
> > 
> > I could not find any "network-related" microos job, and it requires special network setup with two NICs on the same vlan. Do you suggest to schedule in an existing one ?
> 
> Not necessarily, but maybe it would be useful to run some other network related modules in the same job to make sure they work in a bonding setup as well?

that's a good idea, @foursixnine should we concretize it in a ticket for reference ?

**Review by foursixnine — APPROVED** [review]

**Comment by foursixnine** [comment]
> > > > How useful is this as a separate job? It has only a single test module
> > > 
> > > 
> > > I could not find any "network-related" microos job, and it requires special network setup with two NICs on the same vlan. Do you suggest to schedule in an existing one ?
> > 
> > 
> > Not necessarily, but maybe it would be useful to run some other network related modules in the same job to make sure they work in a bonding setup as well?
> 
> that's a good idea, @foursixnine should we concretize it in a ticket for reference ?

please go ahead and create a new one...

**Pull request merged**
