### PR TITLE
Update Leap Micro jobgroup to 6.0

### PR DESCRIPTION
**Pull request by a-kpappas**
The mediums mentioned in the jobgroup have already been created on o3.

Related ticket: https://progress.opensuse.org/issues/157267

### CODE REVIEW

**Review by jlausuch — CHANGES_REQUESTED** [review]
- Remove DVD yaml, not needed any more as there is no more DVD flavors.
- For the images, we need new flavors:
DISTRI=leap-micro (correct)
FLAVOR=similar to SL Micro:
- `Default`
- `Default-encrypted` (only x86_64)
- `Default-qcow`
- `Default-SelfInstall`
- `Default-VMware` (not sure we can run this in O3)
- `Base`
- `Base-encrypted` (only x86_64)
- `Base-qcow`
- `Base-SelfInstall`
- `Base-VMware` (not sure we can run this in O3)

**Comment by lkocman** [comment]
We will be re-adding the RT variant for aarch64 only based on what I heard on the last call.

**Comment by lkocman** [comment]
Just to confirm RT was alraedy brought back and is part of LeapMicro 6.0. I'll make separate PR to incorporate changes as clock is ticking.

**Comment by lkocman** [comment]
Actually I see that DVD is dropped and RT is in there so no change needed.

**Comment by lkocman** [comment]
Can we please merge the request as it is?

**Review by jlausuch — APPROVED** [review]

**Pull request merged**
