### PR TITLE
Fix assests for NET and Enable aarch64 zdup tests

### PR DESCRIPTION
**Pull request by mloviska**

### CODE REVIEW

**Comment by mloviska** [comment]
#### Leap15.3 to Leap15.4 

* [opensuse-15.4-DVD-aarch64-Build238.1-zdup-Leap-15.3-gnome@aarch64](https://openqa.opensuse.org/tests/2374152#)
* [opensuse-15.4-DVD-aarch64-Build238.1-zdup-Leap-15.3-kde@aarch64](https://openqa.opensuse.org/tests/2374154#)

I need to update *leap15.2 aarch64* images and push them to openQA, first. 

@ggardet is it enough to use `http://download.opensuse.org/distribution/leap/15.2/repo/{oss,non-oss}` and `http://download.opensuse.org/update/leap/15.2/{oss,non-oss}/` repos?

**Comment by ggardet** [comment]
> #### Leap15.3 to Leap15.4
> * [opensuse-15.4-DVD-aarch64-Build238.1-zdup-Leap-15.3-gnome@aarch64](https://openqa.opensuse.org/tests/2374152#)
> * [opensuse-15.4-DVD-aarch64-Build238.1-zdup-Leap-15.3-kde@aarch64](https://openqa.opensuse.org/tests/2374154#)
> 
> I need to update _leap15.2 aarch64_ images and push them to openQA, first.
> 
> @ggardet is it enough to use `http://download.opensuse.org/distribution/leap/15.2/repo/{oss,non-oss}` and `http://download.opensuse.org/update/leap/15.2/{oss,non-oss}/` repos?

No, for aarch64:
* Until Leap 15.2 you need to use https://download.opensuse.org/ports/aarch64/distribution/leap/15.2/repo/oss/ and https://download.opensuse.org/update/leap/15.2/oss/
* For Leap 15.3 (and later) you can use the regular repos

**Review by jlausuch — APPROVED** [review]

**Comment by jlausuch** [comment]
@ggardet is it ok to merge?

**Review by ggardet — APPROVED** [review]
LGTM, thanks!

**Comment by asdil12** [comment]
Merging this broke the CI:
```
Checking opensuse_leap_15 -> 50
Error: API call ('-X', 'POST', 'job_templates_scheduling/50', 'schema=JobTemplates-01.yaml', 'preview=1', '--param-file', 'template=job_groups/opensuse_leap_15.yaml') returned exit code '1'
Checking opensuse_leap_15_powerpc -> 51
Error: Error 400:
Job template name 'zdup-Leap-15.2-gnome' with opensuse-Leap-15.4-DVD-aarch64 and aarch64 is already used in job group 'Development Leap'

**Comment by mloviska** [comment]
> Merging this broke the CI:
> 
> ```
> Checking opensuse_leap_15 -> 50
> Error: API call ('-X', 'POST', 'job_templates_scheduling/50', 'schema=JobTemplates-01.yaml', 'preview=1', '--param-file', 'template=job_groups/opensuse_leap_15.yaml') returned exit code '1'
> Checking opensuse_leap_15_powerpc -> 51
> Error: Error 400:
> Job template name 'zdup-Leap-15.2-gnome' with opensuse-Leap-15.4-DVD-aarch64 and aarch64 is already used in job group 'Development Leap'
> ```

I have cleaned up the Dev group. Thanks!

**Pull request merged**
