### PR TITLE
Add opensuse_leap_16.0.yaml

### PR DESCRIPTION
**Pull request by lkocman**
* this is where we'll newly build agama-installer so we can test new builds together with all unreleased package changes

* Use 16.0 rather than 16 as we will most likely have same maintenance workflow like LeapMicro 6.X

* Existing opensuse_leap_16.0_images.yaml will be used for other appliances than agama-installer

Relevant Progress ticket: https://progress.opensuse.org/issues/164141

### CODE REVIEW

**Comment by lkocman** [comment]
@nilxam FYI we shoud probably use 16.0 and not 16 ... as I expect to have project open and just keep on republishing it ... just like with Micro (SLFO does the same).

**Comment by lkocman** [comment]
Related PR https://github.com/os-autoinst/openqa-trigger-from-obs/pull/258

**Comment by foursixnine** [comment]
> I suppose the CI fail is expected since the group 127 doesn't yet exist in openQA.

Likely. I noticed that the messages from the yaml stuff are really bad (not really, they are just having very little info for the user).

It could also be that the medium is not created yet

**Comment by lkocman** [comment]
@Vogtinator what is your thought?

**Comment by lkocman** [comment]
It was the missing medium in https://openqa.opensuse.org/admin/products

**Pull request merged**
