### PR TITLE
Update test with auto-created leap15.4 qcow

### PR DESCRIPTION
**Pull request by lemon-suse**
Related ticket: https://progress.opensuse.org/issues/122173
VR:  https://openqa.opensuse.org/tests/3102576#details

### CODE REVIEW

**Comment by pdostal** [comment]
What about `START_AFTER_TEST`?

**Comment by lemon-suse** [comment]
> What about `START_AFTER_TEST`?

Thanks, you are right, we need it to ensure the test won't start before auto-installation job finished.  PR created for it  https://github.com/os-autoinst/opensuse-jobgroups/pull/269

**Comment by DimStar77** [comment]
Seems to be responsible for this fallout: https://openqa.opensuse.org/tests/3106812

This now expects a tumbleweed-update qcow - which is not what the test is supposed to do (it's supposed to update from 15.4 to tw)

**Comment by lemon-suse** [comment]
> Seems to be responsible for this fallout: https://openqa.opensuse.org/tests/3106812
> 
> This now expects a tumbleweed-update qcow - which is not what the test is supposed to do (it's supposed to update from 15.4 to tw)

Yes, I already have the PR https://github.com/os-autoinst/opensuse-jobgroups/pull/269 but not merged, could you help review and merge?

**Comment by lemon-suse** [comment]
> > Seems to be responsible for this fallout: https://openqa.opensuse.org/tests/3106812
> > This now expects a tumbleweed-update qcow - which is not what the test is supposed to do (it's supposed to update from 15.4 to tw)
> 
> Yes, I already have the PR #269 but not merged, could you help review and merge?

PR merged, should fixed this issue.

**Pull request merged**
