### PR TITLE
Add jeos cloud tests into x86_64 and aarch64 TW groups

### PR DESCRIPTION
**Pull request by mloviska**
All blockers has been resolved and it's ready to be merged. Cloud images
can be tested in QEMU directly

### CODE REVIEW

**Comment by mloviska** [comment]
Waiting for https://github.com/os-autoinst/openqa-trigger-from-obs/pull/248

**Review by grisu48 — APPROVED** [review]

**Comment by grisu48** [comment]
Feel free to merge, I think the CI needs to be retriggered.

**Comment by Vogtinator** [comment]
Is this still WIP?

**Comment by mloviska** [comment]
> Is this still WIP?

The test is still failing, https://openqa.opensuse.org/tests/4402422. I haven't moved it as it looked like the bugs will be addressed promptly

**Comment by Vogtinator** [comment]
> > Is this still WIP?
> 
> The test is still failing, https://openqa.opensuse.org/tests/4402422. I haven't moved it as it looked like the bugs will be addressed promptly

If it's about journal_check, the SRSO one will take a while as it needs kernel + qemu fixes on the QA hosts. It's known already so can be added to the "ignore" list IMO ("ignore" because it's a host issue not a SUT issue)

**Comment by mloviska** [comment]
> If it's about journal_check, the SRSO one will take a while as it needs kernel + qemu fixes on the QA hosts. It's known already so can be added to the "ignore" list IMO ("ignore" because it's a host issue not a SUT issue)

Alright, I will update the known bugs. I can also add https://bugzilla.opensuse.org/show_bug.cgi?id=1227908 as it takes longer than expected to get a fix

**Comment by mloviska** [comment]
VR: https://openqa.opensuse.org/tests/4403154#

**Pull request merged**
