### PR TITLE
Add new test for FIPS on MicroOS

### PR DESCRIPTION
**Pull request by jlausuch**

### CODE REVIEW

**Comment by jlausuch** [comment]
This is the VR: https://openqa.opensuse.org/tests/3149462#step/enable_fips/25
and most likely we need to label it with [boo#1198065](https://bugzilla.opensuse.org/show_bug.cgi?id=1198065)

**Comment by ggardet** [comment]
Please add a VR for aarch64.

**Comment by jlausuch** [comment]
> Please add a VR for aarch64.

https://openqa.opensuse.org/tests/3158602#step/enable_fips/55

**Review by mloviska — APPROVED** [review]

**Review by ggardet — APPROVED** [review]

**Comment by DimStar77** [comment]
https://progress.opensuse.org/issues/125558

**Comment by Vogtinator** [comment]
It's guarded by `unless is_sle_micro` only, which does not care about non-SLE MicroOS.

**Pull request merged**
