### PR TITLE
Containers: Enable kubectl test on Leap15.4

### PR DESCRIPTION
**Pull request by pdostal**
* Code pull request: os-autoinst/os-autoinst-distri-opensuse#15349

### CODE REVIEW

**Comment by grisu48** [comment]
For Tumbleweed the rule is that any job groups changes must first be done in a development group and working for some time before they get merged. I would expect for Leap the same to be valid, so perhaps we first create `kubectl` in the Development group and then move it over here?

**Comment by pdostal** [comment]
image
Let's see what will happen in Development / Leap.

**Comment by pdostal** [comment]
* Verified in `Development / Leap` job group. Now I think ready to merge.

**Comment by grisu48** [comment]
I asked for confirmation in the openSUSE openQA channel and didn't got any objections in 3h, so IMHO this is safe to proceed with.

**Pull request merged**
